services:
  react:
    build:
      context: ./frontend
    environment:
      - API_URL=${API_URL}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/front-end
      - /frontend/node_modules

  api:
    build:
      context: ./backend
    environment:
      - GIN_MODE=${GIN_MODE}
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend
