version: "3.9"
services:
  # React
  react:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    command: yarn run dev
    environment:
      - DJANGO_URL=${DJANGO_URL}
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./front-end:/front-end
      - /front-end/node_modules

  web:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    command: sh /back-end/start.sh
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./back-end:/back-end
